### ISSUE TITLE
load local file is error!!!

### ISSUE THREAD

**Issue by anchengjian** [nwjs/npm-installer#54]
like this in `.npmrc`
```
NWJS_URLBASE=file:///C:/Users/anchengjian/Downloads
```

and I got an error

```
Could not find /C:/Users/anchengjian/Downloads0.20.1/nwjs-sdk-v0.20.1-win-x64.zip
```

**Comment by anchengjian** [comment]
https://github.com/nwjs/npm-installer/blob/master/scripts/install.js#L88-L92

![image](https://cloud.githubusercontent.com/assets/8679331/23984757/30495bfa-0a56-11e7-9285-9449d76b1b21.png)

use `url.parse` parse the `file://` url get an incomplete path, lost letter of information

**Comment by anchengjian** [comment]
https://github.com/nwjs/npm-installer/blob/master/scripts/install.js#L67-L73
``` javascript
function fileExistsAndAvailable(filepath) {
  try {
    return fileExists(parsedUrl.path);
  } catch(err) {
    return false;
  }
}
```
The `fileExistsAndAvailable` got `filepath`, but used `parsedUrl.path` !!!!!
![image](https://cloud.githubusercontent.com/assets/8679331/23985342/8abcba66-0a59-11e7-85c2-b6d32f759c67.png)

**Comment by Mithgol** [comment]
> The `fileExistsAndAvailable` got `filepath`, but used `parsedUrl.path` !!!!!

Fixed by @53ebebdaee79dde40c5bb3ed364ce2ee68771c75 in version 0.22.0-sdk-1 (and newer versions in the future).

Please check if it affects the local-file-related problem.

**Comment by anchengjian** [comment]
Thanks, but there's still a problem.

https://github.com/nwjs/npm-installer/blob/master/scripts/install.js#L88-L96 
```
  if ( !fileExistsAndAvailable(parsedUrl.path) ) {
    logError('Could not find ' + parsedUrl.path);
  }
  new Decompress()
    .src( parsedUrl.path )
    .dest( dest )
    .use( Decompress.zip(decompressOptions) )
    .use( Decompress.targz(decompressOptions) )
    .run( cb );
```
In this code, `parsedUrl.path`'s result is `/Download/`, lost the `D:`. 

This problem can be resolve by `D;/Download/`
```
  var filePath = require('path').resolve(url.slice(7));
  
  if ( !fileExistsAndAvailable(filePath) ) {
    logError('Could not find ' + parsedUrl.path);
  }
  new Decompress()
    .src( filePath )
    .dest( dest )
    .use( Decompress.zip(decompressOptions) )
    .use( Decompress.targz(decompressOptions) )
    .run( cb );
```

**Comment by Mithgol** [comment]
Fixed by @8d658c66d113279f661a6f846304cdab90235e50 in version 0.22.0-sdk-2 (and newer versions in the future).

Please check again if it affects the local-file-related problem.

I have replaced `7` by `'file://'.length` (for clarity) and added `decodeURIComponent()` (for URLs like `'file://D:\\My%20Downloads\\'` to be converted to `'D:\\My Downloads\\'` before `fileExistsAndAvailable()` is called).

**Comment by anchengjian** [comment]
This problem is fixed. 

https://github.com/nwjs/npm-installer/blob/master/scripts/install.js#L95 
This error log is `parsedUrl.path` ...

![image](https://cloud.githubusercontent.com/assets/8679331/25415445/3d4c6fca-2a6a-11e7-9e70-cde6a366f42a.png)

**Comment by Mithgol** [comment]
Fixed by @471f6aae6a22bbbdec13fbc544c76e49cd04fe23 in version 0.22.0-sdk-3 (and newer versions in the future).
